In [1]:
import pandas as pd
import numpy as np

In [16]:
from sklearn.datasets import load_iris
iris = load_iris()




In [17]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [26]:
#logistic regression
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

C:\Users\Ankith\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [27]:
#Logistic Regression accuracy
np.average(l_scores)

0.9733333333333334

In [21]:
#Decision tree
df_score = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
df_score

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [28]:
#Decision Tree accuracy
np.average(df_score)

0.9533333333333334

In [23]:
#Support Vector Machine
svm_score = cross_val_score(SVC(),iris.data,iris.target)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [29]:
#SVM accuracy
np.average(svm_score)

0.9666666666666666

In [24]:
#Random Forest
rf_score = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [30]:
#Random Forest Accuracy
np.average(rf_score)

0.9666666666666668

In [33]:
result = pd.DataFrame(
    { 'Model' :['Logistic Regression' , 'Decision Tree Classifier' , 'Support Vector Machine' , 'Random Forest' ],
       'Scores' : [np.average(l_scores) , np.average(df_score) , np.average(svm_score) , np.average(rf_score)]
        
    })

results = result.sort_values(by='Scores',ascending = True)
results

Model    Scores
1  Decision Tree Classifier  0.953333
2    Support Vector Machine  0.966667
3             Random Forest  0.966667
0       Logistic Regression  0.973333